parameters:
    letdoittoday.rabbitmq:
        host: '%env(string:RABBITMQ_HOST)%'
        port: '%env(int:RABBITMQ_PORT)%'
        username: '%env(string:RABBITMQ_USERNAME)%'
        password: '%env(string:RABBITMQ_PASSWORD)%'
